# disable in production:
local_backend: true
# command to run a local Decap instance: npx-decap-server

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/upload"
public_folder: "/"

site_url: https://agnieszka-stobierska.eu

media_library:
  name: cloudinary
  config:
    cloud_name: dgdzhzjbf
    api_key: 137947945749348

# SEO anchor:
seo: &seo
  name: "SEOmetaData"
  label: "SEO"
  widget: "object"
  collapsed: true
  fields:
    - {
        name: "metaTitle",
        label: "SEO Title",
        widget: "string",
        default: "{{ title }}",
        required: true,
      }
    - {
        name: "metaDescription",
        label: "SEO Description",
        widget: "string",
        pattern: [".{20,160}", "between 20 and 160 characters"],
        required: true,
        hint: "must be between 20 and 160 characters",
      }
    - { name: "metaImage", label: "SEO image", widget: "image" }
    - {
        name: "keywords",
        label: "keywords",
        widget: "string",
        hint: "keywords are comma seperated",
        required: false,
      }

collections:
  - name: "main"
    label: "Main"
    files:
      - label: "About"
        name: "about"
        file: "content/main/about.md"
        fields:
          - { lablel: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Experience", name: "experience", widget: "markdown" }
